using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace OdeToFood.Web.Controllers
{
    public class ContactController : IController
    {
        public ContactController(ILogginService loggin) { 

        }

        public void Execute(RequestContext requestContext)
        {
            HttpContext.Current.Response.Write("This was generated by our custom IController class");
        }     
    }
}